### ISSUE TITLE
IST - India Standard Time missing

### ISSUE THREAD

**Issue by thomas-crowe** [BarRaider/streamdeck-worldtime#3]
The option to set a timezone that is 5 &1/2 hours ahead of UTC is not present.

**Comment by nledenyi** [comment]
+1

**Comment by AsianOcean** [comment]
+1

**Comment by AsianOcean** [comment]
Correct time cannot be selected for India. Whatever available is 30 minutes off. Nepal time is 45 minutes off. At least if there was a manual selection available, such as Greenwich plus or minus, that would have helped.

**Comment by gmacdev** [comment]
+1

**Comment by BarRaider** [comment]
<60 min time zones are now supported in latest version
