### ISSUE TITLE
Duplicated a timezone button, now all times vanished from all buttons.

### ISSUE THREAD

**Issue by skeletonbow** [BarRaider/streamdeck-worldtime#7]
I had timezones for Budapest, Amsterdam, Sydney, London each on their own button.  I right click and copied the Sydney one and pasted it on another button, then edited this new button to be for Berlin.  The button showed stuck on Sydney however and would not update to show Berlin.  I quit the Elgato software and restarted it and now all 5 worldtime buttons show only the background globe graphic with no time display at all.

**Comment by bartusek27** [comment]
I might have a same problem.

**Comment by skeletonbow** [comment]
Update:  The problem temporarily went away several days after I reported it, and has now come back again with none of the clocks working.  This includes after killing StreamDeck.exe and its subprocesses, as well as rebooting. Problem still remains.

**Comment by BarRaider** [comment]
Please try latest version v1.6 and report if still happening
